#!/usr/bin/env python3
"""
Post-build step for the React app. Two transformations:

1. Strip WordPress/Divi chrome that's baked into the React index.html
   from when the app was originally generated by ReactPress on .151:
   - <header id="main-header"> (logo + WP top nav linking back to .151)
   - <footer class="et-l et-l--footer"> (Divi footer)

2. Inject the TW2 unified header (logo + nav + Upgrade) right before
   <div id="root"> so /app/ shows the same site nav as marketing pages.
   Hidden on mobile via CSS - React's mobile layouts own that screen.

Idempotent: safe to run multiple times. Run after every `npm run build`.
"""
from pathlib import Path
import re
import sys

BUILD_INDEX = Path("/home/flask/web-react/build/index.html")
HEADER_PARTIAL = Path("/var/www/tradewave/_partials/tw_app_header.html")
MARKER = '<div id="root">'
SENTINEL = "tw-app-header"


def strip_wp_chrome(src: str) -> tuple[str, bool]:
    """Remove WP/Divi header and footer markup. Returns (new_src, changed)."""
    new_src = src
    # WP main header
    new_src = re.sub(
        r'<header id="main-header"[^>]*>.*?</header>(?:<!--[^>]*-->)?',
        '',
        new_src,
        flags=re.DOTALL,
    )
    # Divi footer
    new_src = re.sub(
        r'<footer class="et-l et-l--footer">.*?</footer>',
        '',
        new_src,
        flags=re.DOTALL,
    )
    return new_src, new_src != src


def inject_header(src: str) -> tuple[str, bool]:
    """Insert TW2 header partial before <div id="root">. Skip if already there."""
    if SENTINEL in src:
        return src, False
    if MARKER not in src:
        raise RuntimeError(f"marker {MARKER!r} not in build/index.html")
    header = HEADER_PARTIAL.read_text()
    # Stub for React's footer-height calc (App.js looks for .et-l when debug=False).
    # Hidden, so clientHeight=0 - preserves React's arithmetic without visible chrome.
    header = '<div class="et-l" style="display:none"></div>' + header
    # In /app context the React shell spans 100vw - make the header span the same
    # by overriding the partial's max-width: 1200px. Home page keeps the partial as-is.
    app_override = (
        '<style id="tw-app-header-app-override">'
        '#main-header.tw-header .tw-container{max-width:none !important;padding:12px 32px !important;}'
        '</style>'
    )
    new_src = src.replace(MARKER, header + "\n" + app_override + "\n" + MARKER, 1)
    return new_src, True


def main() -> int:
    if not BUILD_INDEX.exists():
        print(f"ERROR: build not found: {BUILD_INDEX}", file=sys.stderr)
        return 1
    if not HEADER_PARTIAL.exists():
        print(f"ERROR: header partial not found: {HEADER_PARTIAL}", file=sys.stderr)
        return 1

    src = BUILD_INDEX.read_text()
    original_size = len(src)

    src, stripped = strip_wp_chrome(src)
    src, injected = inject_header(src)

    if stripped or injected:
        BUILD_INDEX.write_text(src)
        print(f"WP chrome stripped: {stripped}")
        print(f"TW2 header injected: {injected}")
        print(f"Size: {original_size} -> {len(src)} bytes")
    else:
        print("No changes (already processed).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
